fixtures:
  repositories:
    logrotate:
      repo: "https://github.com/rodjek/puppet-logrotate.git"
      ref: "1.1.1"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.1.0"
  symlinks:
    masterless: "#{source_dir}"

