name 'tohuwabohu-masterless'
version '1.0.0'
source 'https://github.com/tohuwabohu/puppet-masterless.git'
project_page 'https://github.com/tohuwabohu/puppet-masterless'
author 'Martin Meinhold'
license 'Apache License, Version 2.0'
summary 'Install and manage Puppet in masterless mode.'
description ''

dependency 'rodjek/logrotate', '1.x'
dependency 'example42/puppi', '2.x'
dependency 'puppetlabs/stdlib', '4.x'
